
public class MainClass 
{
	public static void main(String[] args) 
	{
		new org.apache.commons.collections.BulkTest("test").run();
		new org.apache.commons.collections.MapPerformance();
		new org.apache.commons.collections.TestAll("test").run();
		new org.apache.commons.collections.TestAllPackages("test").run();
//		new org.apache.commons.collections.TestArrayList().run();
		new org.apache.commons.collections.TestArrayStack("test").run();
		new org.apache.commons.collections.TestBagUtils("test").run();
		new org.apache.commons.collections.TestBeanMap("test").run();
		new org.apache.commons.collections.TestBinaryHeap("test").run();
		new org.apache.commons.collections.TestBoundedFifoBuffer("test").run();
		new org.apache.commons.collections.TestBoundedFifoBuffer2("test").run();
		new org.apache.commons.collections.TestBufferUtils("test").run();
		new org.apache.commons.collections.TestClosureUtils("test").run();
//		new org.apache.commons.collections.TestCollectionUtils("test").run();
		new org.apache.commons.collections.TestCursorableLinkedList("test").run();
		new org.apache.commons.collections.TestDoubleOrderedMap("test").run();
		new org.apache.commons.collections.TestEnumerationUtils("test").run();
		new org.apache.commons.collections.TestExtendedProperties("test").run();
		new org.apache.commons.collections.TestFactoryUtils("test").run();
		new org.apache.commons.collections.TestFastArrayList("test").run();
		new org.apache.commons.collections.TestFastArrayList1("test").run();
		new org.apache.commons.collections.TestFastHashMap("test").run();
		new org.apache.commons.collections.TestFastHashMap1("test").run();
		new org.apache.commons.collections.TestFastTreeMap("test").run();
		new org.apache.commons.collections.TestFastTreeMap1("test").run();
		new org.apache.commons.collections.TestHashBag("test").run();
		new org.apache.commons.collections.TestIteratorUtils("test").run();
//		new org.apache.commons.collections.TestLinkedList("test").run();
		new org.apache.commons.collections.TestListUtils("test").run();
		new org.apache.commons.collections.TestLRUMap("test").run();
		new org.apache.commons.collections.TestMapUtils("test").run();
//		new org.apache.commons.collections.TestMultiHashMap("test").run();
		new org.apache.commons.collections.TestPredicateUtils("test").run();
		new org.apache.commons.collections.TestReferenceMap("test").run();
		new org.apache.commons.collections.TestSequencedHashMap("test").run();
		new org.apache.commons.collections.TestSetUtils("test").run();
		new org.apache.commons.collections.TestStaticBucketMap("test").run();
		new org.apache.commons.collections.TestTransformerUtils("test").run();
		new org.apache.commons.collections.TestTreeBag("test").run();
//		new org.apache.commons.collections.TestTreeMap("test").run();
//		new org.apache.commons.collections.TestTypedCollection("test").run();
		new org.apache.commons.collections.TestUnboundedFifoBuffer("test").run();
		
		new org.apache.commons.collections.bag.TestAll("test").run();
		new org.apache.commons.collections.bag.TestHashBag("test").run();
		new org.apache.commons.collections.bag.TestPredicatedBag("test").run();
		new org.apache.commons.collections.bag.TestPredicatedSortedBag("test").run();
		new org.apache.commons.collections.bag.TestTransformedBag("test").run();
		new org.apache.commons.collections.bag.TestTransformedSortedBag("test").run();
		new org.apache.commons.collections.bag.TestTreeBag("test").run();
		new org.apache.commons.collections.bag.TestTypedBag("test").run();
		new org.apache.commons.collections.bag.TestTypedSortedBag("test").run();
		
//		new org.apache.commons.collections.bidimap.AbstractTestBidiMap("test").run();
		new org.apache.commons.collections.bidimap.TestAbstractOrderedBidiMapDecorator("test").run();
		new org.apache.commons.collections.bidimap.TestAll("test").run();
		new org.apache.commons.collections.bidimap.TestDualHashBidiMap("test").run();
		new org.apache.commons.collections.bidimap.TestDualTreeBidiMap("test").run();
		new org.apache.commons.collections.bidimap.TestDualTreeBidiMap2("test").run();
		new org.apache.commons.collections.bidimap.TestTreeBidiMap("test").run();
		new org.apache.commons.collections.bidimap.TestUnmodifiableBidiMap("test").run();
		new org.apache.commons.collections.bidimap.TestUnmodifiableOrderedBidiMap("test").run();
		new org.apache.commons.collections.bidimap.TestUnmodifiableSortedBidiMap("test").run();

		new org.apache.commons.collections.buffer.TestAll("test").run();
		new org.apache.commons.collections.buffer.TestBlockingBuffer("test").run();
		new org.apache.commons.collections.buffer.TestBoundedBuffer("test").run();
		new org.apache.commons.collections.buffer.TestBoundedFifoBuffer("test").run();
		new org.apache.commons.collections.buffer.TestBoundedFifoBuffer2("test").run();
		new org.apache.commons.collections.buffer.TestCircularFifoBuffer("test").run();
//		new org.apache.commons.collections.buffer.TestPredicatedBuffer("test").run();
		new org.apache.commons.collections.buffer.TestPriorityBuffer("test").run();
		new org.apache.commons.collections.buffer.TestSynchronizedBuffer("test").run();
		new org.apache.commons.collections.buffer.TestTransformedBuffer("test").run();
		new org.apache.commons.collections.buffer.TestUnboundedFifoBuffer("test").run();
		new org.apache.commons.collections.buffer.TestUnmodifiableBuffer("test").run();
		
//		new org.apache.commons.collections.collection.AbstractTestCollection("test").run();
		new org.apache.commons.collections.collection.TestAll("test").run();
		new org.apache.commons.collections.collection.TestCompositeCollection("test").run();
//		new org.apache.commons.collections.collection.TestPredicatedCollection("test").run();
		new org.apache.commons.collections.collection.TestSynchronizedCollection("test").run();
		new org.apache.commons.collections.collection.TestTransformedCollection("test").run();
		new org.apache.commons.collections.collection.TestUnmodifiableCollection("test").run();

//		new org.apache.commons.collections.comparators.AbstractTestComparator("test").run();
		new org.apache.commons.collections.comparators.TestAll("test").run();
		new org.apache.commons.collections.comparators.TestBooleanComparator("test").run();
		new org.apache.commons.collections.comparators.TestComparableComparator("test").run();
		new org.apache.commons.collections.comparators.TestComparatorChain("test").run();
		new org.apache.commons.collections.comparators.TestFixedOrderComparator("test").run();
//		new org.apache.commons.collections.comparators.TestNullComparator("test").run();
		new org.apache.commons.collections.comparators.TestReverseComparator("test").run();
		
//		new org.apache.commons.collections.iterators.AbstractTestIterator("test").run();
//		new org.apache.commons.collections.iterators.AbstractTestListIterator("test").run();
//		new org.apache.commons.collections.iterators.AbstractTestMapIterator("test").run();
//		new org.apache.commons.collections.iterators.AbstractTestOrderedMapIterator("test").run();
		new org.apache.commons.collections.iterators.TestAll("test").run();
		new org.apache.commons.collections.iterators.TestArrayIterator("test").run();
		new org.apache.commons.collections.iterators.TestArrayIterator2("test").run();
		new org.apache.commons.collections.iterators.TestArrayListIterator("test").run();
		new org.apache.commons.collections.iterators.TestArrayListIterator2("test").run();
		new org.apache.commons.collections.iterators.TestCollatingIterator("test").run();
		new org.apache.commons.collections.iterators.TestFilterIterator("test").run();
		new org.apache.commons.collections.iterators.TestFilterListIterator("test").run();
		new org.apache.commons.collections.iterators.TestIteratorChain("test").run();
		new org.apache.commons.collections.iterators.TestListIteratorWrapper("test").run();
		new org.apache.commons.collections.iterators.TestLoopingIterator("test").run();
		new org.apache.commons.collections.iterators.TestLoopingListIterator("test").run();
		new org.apache.commons.collections.iterators.TestObjectArrayIterator("test").run();
		new org.apache.commons.collections.iterators.TestObjectArrayListIterator("test").run();
		new org.apache.commons.collections.iterators.TestObjectArrayListIterator2("test").run();
		new org.apache.commons.collections.iterators.TestObjectGraphIterator("test").run();
		new org.apache.commons.collections.iterators.TestReverseListIterator("test").run();
		new org.apache.commons.collections.iterators.TestSingletonIterator("test").run();
		new org.apache.commons.collections.iterators.TestSingletonIterator2("test").run();
		new org.apache.commons.collections.iterators.TestSingletonListIterator("test").run();
		new org.apache.commons.collections.iterators.TestUniqueFilterIterator("test").run();
		new org.apache.commons.collections.iterators.TestUnmodifiableIterator("test").run();
		new org.apache.commons.collections.iterators.TestUnmodifiableListIterator("test").run();
		new org.apache.commons.collections.iterators.TestUnmodifiableMapIterator("test").run();
		new org.apache.commons.collections.iterators.TestUnmodifiableOrderedMapIterator("test").run();
		
//		new org.apache.commons.collections.keyvalue.AbstractTestMapEntry("test").run();
		new org.apache.commons.collections.keyvalue.TestAll("test").run();
		new org.apache.commons.collections.keyvalue.TestDefaultKeyValue("test").run();
		new org.apache.commons.collections.keyvalue.TestDefaultMapEntry("test").run();
		new org.apache.commons.collections.keyvalue.TestMultiKey("test").run();
		new org.apache.commons.collections.keyvalue.TestTiedMapEntry("test").run();
		new org.apache.commons.collections.keyvalue.TestUnmodifiableMapEntry("test").run();
		
//		new org.apache.commons.collections.list.AbstractTestList("test").run();
//		new org.apache.commons.collections.list.TestAbstractLinkedList("test").run();
		new org.apache.commons.collections.list.TestAll("test").run();
		new org.apache.commons.collections.list.TestCursorableLinkedList("test").run();
		new org.apache.commons.collections.list.TestFixedSizeList("test").run();
		new org.apache.commons.collections.list.TestGrowthList("test").run();
		new org.apache.commons.collections.list.TestNodeCachingLinkedList("test").run();
//		new org.apache.commons.collections.list.TestPredicatedList("test").run();
		new org.apache.commons.collections.list.TestSetUniqueList("test").run();
		new org.apache.commons.collections.list.TestSynchronizedList("test").run();
		new org.apache.commons.collections.list.TestTransformedList("test").run();
		new org.apache.commons.collections.list.TestTreeList("test").run();
		new org.apache.commons.collections.list.TestTypedList("test").run();
		new org.apache.commons.collections.list.TestUnmodifiableList("test").run();
		
//		new org.apache.commons.collections.map.AbstractTestIterableMap("test").run();
//		new org.apache.commons.collections.map.AbstractTestMap("test").run();
//		new org.apache.commons.collections.map.AbstractTestOrderedMap("test").run();
//		new org.apache.commons.collections.map.AbstractTestSortedMap("test").run();
		new org.apache.commons.collections.map.TestAll("test").run();
		new org.apache.commons.collections.map.TestCaseInsensitiveMap("test").run();
		new org.apache.commons.collections.map.TestCompositeMap("test").run();
		new org.apache.commons.collections.map.TestDefaultedMap("test").run();
		new org.apache.commons.collections.map.TestFixedSizeMap("test").run();
		new org.apache.commons.collections.map.TestFixedSizeSortedMap("test").run();
		new org.apache.commons.collections.map.TestFlat3Map("test").run();
		new org.apache.commons.collections.map.TestHashedMap("test").run();
		new org.apache.commons.collections.map.TestIdentityMap("test").run();
		new org.apache.commons.collections.map.TestLazyMap("test").run();
		new org.apache.commons.collections.map.TestLazySortedMap("test").run();
		new org.apache.commons.collections.map.TestLinkedMap("test").run();
		new org.apache.commons.collections.map.TestListOrderedMap("test").run();
		new org.apache.commons.collections.map.TestListOrderedMap2("test").run();
		new org.apache.commons.collections.map.TestLRUMap("test").run();
		new org.apache.commons.collections.map.TestMultiKeyMap("test").run();
		new org.apache.commons.collections.map.TestMultiValueMap("test").run();
//		new org.apache.commons.collections.map.TestPredicatedMap("test").run();
//		new org.apache.commons.collections.map.TestPredicatedSortedMap("test").run();
		new org.apache.commons.collections.map.TestReferenceIdentityMap("test").run();
		new org.apache.commons.collections.map.TestReferenceMap("test").run();
		new org.apache.commons.collections.map.TestSingletonMap("test").run();
		new org.apache.commons.collections.map.TestStaticBucketMap("test").run();
		new org.apache.commons.collections.map.TestTransformedMap("test").run();
		new org.apache.commons.collections.map.TestTransformedSortedMap("test").run();
		new org.apache.commons.collections.map.TestUnmodifiableMap("test").run();
		new org.apache.commons.collections.map.TestUnmodifiableOrderedMap("test").run();
		new org.apache.commons.collections.map.TestUnmodifiableSortedMap("test").run();
		
//		new org.apache.commons.collections.set.AbstractTestSet("test").run();
//		new org.apache.commons.collections.set.AbstractTestSortedSet("test").run();
		new org.apache.commons.collections.set.TestAll("test").run();
		new org.apache.commons.collections.set.TestCompositeSet("test").run();
		new org.apache.commons.collections.set.TestListOrderedSet("test").run();
		new org.apache.commons.collections.set.TestListOrderedSet2("test").run();
		new org.apache.commons.collections.set.TestMapBackedSet("test").run();
		new org.apache.commons.collections.set.TestMapBackedSet2("test").run();
//		new org.apache.commons.collections.set.TestPredicatedSet("test").run();
//		new org.apache.commons.collections.set.TestPredicatedSortedSet("test").run();
		new org.apache.commons.collections.set.TestSynchronizedSet("test").run();
		new org.apache.commons.collections.set.TestSynchronizedSortedSet("test").run();
		new org.apache.commons.collections.set.TestTransformedSet("test").run();
		new org.apache.commons.collections.set.TestTransformedSortedSet("test").run();
		new org.apache.commons.collections.set.TestTypedSet("test").run();
		new org.apache.commons.collections.set.TestTypedSortedSet("test").run();
		new org.apache.commons.collections.set.TestUnmodifiableSet("test").run();
		new org.apache.commons.collections.set.TestUnmodifiableSortedSet("test").run();
		
	}
}
